import logging
from datetime import datetime
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class PDFHealthPassportGenerator:
    def generate_html_passport(
        self,
        patient_info: Dict[str, Any],
        profile_info: Dict[str, Any],
        vitals_history: List[Dict[str, Any]],
        medical_reports: List[Dict[str, Any]]
    ) -> str:
        """
        Generates a printable, styled HTML Medical Health Passport document
        suitable for physical printing, browser PDF export, or doctor review.
        """
        email = patient_info.get("email", "N/A")
        facility = patient_info.get("facility_name") or "Primary Health Center"
        
        age = profile_info.get("age", "N/A")
        gender = profile_info.get("gender", "N/A")
        medications = ", ".join(profile_info.get("active_medications", [])) or "None reported"
        allergies = ", ".join(profile_info.get("allergies", [])) or "No known allergies"
        history = ", ".join(profile_info.get("medical_history", [])) or "None reported"

        vitals_rows = ""
        for v in vitals_history[:10]:
            sys_bp = v.get("systolic_bp") or "N/A"
            dia_bp = v.get("diastolic_bp") or "N/A"
            sugar = v.get("blood_sugar") or "N/A"
            creat = v.get("creatinine") or "N/A"
            date = v.get("recorded_at", "N/A")[:10]
            vitals_rows += f"<tr><td>{date}</td><td>{sys_bp}/{dia_bp} mmHg</td><td>{sugar} mg/dL</td><td>{creat} mg/dL</td></tr>\n"

        if not vitals_rows:
            vitals_rows = "<tr><td colspan='4'>No recent vital logs available</td></tr>"

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MedGuard Patient Health Passport</title>
    <style>
        body {{ font-family: 'Helvetica', 'Arial', sans-serif; margin: 40px; color: #1e293b; background: #fff; }}
        .header {{ border-bottom: 3px solid #2563eb; padding-bottom: 15px; margin-bottom: 25px; display: flex; justify-content: space-between; align-items: center; }}
        .title {{ font-size: 24px; font-weight: bold; color: #1e3a8a; }}
        .subtitle {{ font-size: 14px; color: #64748b; margin-top: 4px; }}
        .section-title {{ font-size: 16px; font-weight: bold; color: #1e40af; border-left: 4px solid #2563eb; padding-left: 10px; margin: 25px 0 12px 0; }}
        .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }}
        .label {{ font-size: 12px; color: #64748b; font-weight: bold; text-transform: uppercase; }}
        .value {{ font-size: 14px; color: #0f172a; font-weight: 600; margin-top: 2px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ border: 1px solid #e2e8f0; padding: 10px; text-align: left; font-size: 13px; }}
        th {{ background: #f1f5f9; color: #334155; font-weight: bold; }}
        .footer {{ margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="title">MedGuard Clinical Health Passport</div>
            <div class="subtitle">Clinical Decision Support & Chronic Disease Summary</div>
        </div>
        <div style="text-align: right;">
            <div style="font-size: 12px; color: #64748b;">Generated Date</div>
            <div style="font-weight: bold; font-size: 14px;">{datetime.utcnow().strftime('%Y-%m-%d')}</div>
        </div>
    </div>

    <div class="section-title">Patient Demographics & Profile</div>
    <div class="grid">
        <div><div class="label">Patient Email</div><div class="value">{email}</div></div>
        <div><div class="label">Registered Facility</div><div class="value">{facility}</div></div>
        <div><div class="label">Age / Gender</div><div class="value">{age} years / {gender}</div></div>
        <div><div class="label">Known Allergies</div><div class="value" style="color: #dc2626;">{allergies}</div></div>
        <div style="grid-column: span 2;"><div class="label">Active Medications</div><div class="value">{medications}</div></div>
        <div style="grid-column: span 2;"><div class="label">Medical History</div><div class="value">{history}</div></div>
    </div>

    <div class="section-title">Recent Vital Signs Log</div>
    <table>
        <thead>
            <tr><th>Date</th><th>Blood Pressure</th><th>Blood Glucose</th><th>Serum Creatinine</th></tr>
        </thead>
        <tbody>
            {vitals_rows}
        </tbody>
    </table>

    <div class="footer">
        Confidential Clinical Report • Generated by MedGuard Automated Decision Support System • Disclaimer: For clinical review only.
    </div>
</body>
</html>"""
        return html_content

pdf_generator = PDFHealthPassportGenerator()
